language: c
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work/install"
addons:
  apt:
    packages:
    - libgmp-dev
matrix:
  include:
  - env: STACK_YAML=stack.yaml RELEASE_FN=ghc8-pandoc-1-19
    compiler: ": #Pandoc 1.19"
  - env: STACK_YAML=stack.yaml RELEASE_FN=ghc8-pandoc-1-19
    compiler: ": #Pandoc 1.19"
    os: osx
before_install:
- unset CC
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then STACK_OS=osx-x86_64 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then STACK_OS=linux-x86_64 ; fi
- travis_retry curl -L https://www.stackage.org/stack/$STACK_OS | tar xz --strip-components=1
  -C ~/.local/bin
- stack --no-terminal setup
script:
- stack --no-terminal test
before_deploy:
- stack --no-terminal install
- tar czf "$TRAVIS_BUILD_DIR/pandoc-emphasize-code-${TRAVIS_OS_NAME}-${RELEASE_FN}.tar.gz" -C "$HOME/.local/bin/" "./pandoc-emphasize-code"
deploy:
  provider: releases
  api_key:
    secure: ZO2aw3PAMUgBpueiCF/bPZkF0K/kTCnCAlwYNcAy1EZpVPjVfBfq3NjkhpEnoVxWI4N9Fqdg+Td8Um6G0EOrWnIycKQg4xrDfkVI83w3+8Ef/DHhgzSSsbZcrL2CJJpiq02uXcX0y8YL4LpNzEtqY6kcnrcf1dlva70qnUaMhjRu3E5EbFzqq9jdzf8M8FWVwIMaG2WBKNUHzq06w6J54F1ubZ9ON9yVyAgmb8u+xBMSsDvXMJIlfSnMP16mQ8m2LZBIZp2EP93h0aTe5+hlWhFAHoliKVjhPKUDJ3lE4zut3luHDJbpyvCMw4GI/MdiOKJ5cdAUBQZUBqp5GA++XC+ygE17jrLP2DFAq3s3+eUBfNWNK1VXLh5p5uHmPCqqyxBbR53lLUs5A2njXtEAE4CgVXBw/cmWZ7oVYcYWMVdvw+fITI3cqHXk+jbYPslnyn9FVdegXO7hSXIjG73/DIAOnFll4mKY14ylnCeiCqv6Eb+uglQR/1gPAwhyYuJfvW+IvGYK4L9vRnqDH48PGGZZLHsF7KGYx13Pb8oJKffHlxPeE4rLaHJoBoIcFKdJe9742vucebnCyHbhXmiX4NRc2cUkOPpknwiAmpLF8AP0sjO94yNlaMHbSE9FE6ZEzF3Ya02QttxxSiYuWVpkoKB6EZvURS3SwOrbNyK8/kY=
  file: "$TRAVIS_BUILD_DIR/pandoc-emphasize-code-${TRAVIS_OS_NAME}-${RELEASE_FN}.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: owickstrom/pandoc-emphasize-code
    tags: true
